services:
  gateway:
    image: tensorzero/gateway
    volumes:
      - ./config:/app/config:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:?Environment variable OPENAI_API_KEY must be set.}
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "3001:3000"
