services:
  # clickhouse:
  #   image: clickhouse/clickhouse-server:24.12-alpine
  #   environment:
  #     - CLICKHOUSE_USER=chuser
  #     - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
  #     - CLICKHOUSE_PASSWORD=chpassword
  #   ports:
  #     - "8123:8123" # HTTP port
  #     - "9000:9000" # Native port
  #   ulimits:
  #     nofile:
  #       soft: 262144
  #       hard: 262144
  #   healthcheck:
  #     test: wget --spider --tries 1 http://chuser:chpassword@clickhouse:8123/ping
  #     start_period: 30s
  #     start_interval: 1s
  #     timeout: 1s

  gateway:
    image: tensorzero/gateway
    volumes:
      - ./config:/app/config:ro
    environment:
      # - TENSORZERO_CLICKHOUSE_URL=http://chuser:chpassword@clickhouse:8123/tensorzero
      - OPENAI_API_KEY=${OPENAI_API_KEY:?Environment variable OPENAI_API_KEY must be set.}
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "3001:3000"
    # depends_on:
    #   clickhouse:
    #     condition: service_healthy

  # ui:
  #   image: tensorzero/ui
  #   volumes:
  #     Mount our tensorzero.toml file into the container
  #     - ./config:/app/config:ro
  #   environment:
  #     - TENSORZERO_CLICKHOUSE_URL=http://chuser:chpassword@clickhouse:8123/tensorzero
  #     - OPENAI_API_KEY=${OPENAI_API_KEY:?Environment variable OPENAI_API_KEY must be set.}
  #   env_file:
  #     - ${ENV_FILE:-.env}
  #   ports:
  #     - "4001:4001"
  #   depends_on:
  #     clickhouse:
  #       condition: service_healthy
